### ISSUE TITLE
Comparison with other API frameworks?

### ISSUE THREAD

**Issue by karlicoss** [unmade/apiwrappers#49]
Hey, looks cool, I really like using standard dataclasses and type annotations for defining request/reponses! Often you have to define some custom types instead and it's really annoying.

I wonder if you've considered adding that to existing API frameworks? E.g. [Fastapi](https://fastapi.tiangolo.com)? In either case would be cool to have a brief feature comparison with couple of other most popular ones.

**Comment by unmade** [comment]
@karlicoss

Thanks for checking out the library! 

I'm not sure I fully understand what you mean by "comparison with other API frameworks". Can you please elaborate a little more or maybe give some example?

I do indeed used `apiwrappers` with FastAPI, and support for [httpx](https://github.com/encode/httpx) as a driver is coming soon.

**Comment by karlicoss** [comment]
Sorry for the confusion! It's my bad, I missed the 'API clients' part, so I guess it doesn't make sense  to compare it with fastapi, which is more to build API backends.

Don't remember seeing anything similar for the client parts, so perhaps there isn't much to compare with :)

**Comment by unmade** [comment]
Sure, no worries! 

> Don't remember seeing anything similar for the client parts

That's exactly why I made this library :)
